name: Notify on Commit

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add a comment to an issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.MY_PAT }} # si fork
          repository: ${{ github.repository }}
          issue-number: 1
          body: "📢 Notifications de commit #1 — Nouveau commit effectué par ${{ github.actor }} !"
